services:
  web:
    container_name: web
    build:
      context: ./docker/nginx
    ports:
      - 8080:80    
    volumes:
      - ./:/appdata/www
    networks:
      - network
    depends_on:
      - php

  php:
    container_name: php
    build:
      context: ./docker/php
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 0
#      XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005 # Linux users
#      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9005 # MacOS users
    volumes:
      - ./:/appdata/www
#      - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini # Linux users
#      - ./docker/php/xdebug-macos.ini:/usr/local/etc/php/conf.d/xdebug.ini # MacOS users
#      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    networks:
      - network
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:9.1
    ports:
      - 40000:3306
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: wwwuser
      MYSQL_PASSWORD: www4s3r
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - database-data:/var/lib/mysql
    networks:
      - network

volumes:
  database-data:

networks:
  network:
    external: true