services:
#  web:
#    container_name: web
#    build:
#      context: ./docker/nginx
#    ports:
#      - "8080:80"
#    volumes:
#      - ./:/var/www
#    networks:
#      - network
#    depends_on:
#      - php
#
#  php:
#    container_name: php
#    build:
#      context: ./docker/php
#    environment:
#      PHP_IDE_CONFIG: serverName=Docker
#      PHP_XDEBUG_ENABLED: 0
#    volumes:
#      - ./:/var/www
#    networks:
#      - network
#    depends_on:
#      - db
#
  db:
    container_name: db
    image: mysql:9.1
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - mysql-storage:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-storage:

networks:
  network:
