services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    restart: always
    working_dir: /var/www/
    volumes:
      - ..:/var/www

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ..:/var/www
      - ./nginx:/etc/nginx/conf.d